[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[env]
# These will be set through Railway's environment variables interface
DISCORD_TOKEN = { default = "" }
CREATURE_CHANNEL_ID = { default = "" }
BOSS_CHANNEL_ID = { default = "" }
